### Importing library and basic array

In [12]:
import numpy as np

a = np.array([[1,2],[3,4]], dtype="int16")
print(a)

[[1 2]
 [3 4]]


### Printing characteristcs of an Array

In [7]:
a.ndim  # number of dimentions

2

In [8]:
a.shape # shape of the array - this is a tuple with dimention's size

(2, 2)

In [9]:
a.dtype # basic data type

dtype('int8')

In [14]:
a.size # number of elements in the array

4

In [13]:
a.nbytes # number of bytes used in the array

8

In [16]:
a.itemsize # number of bytes of data type

2

### Accessing and updating elements in array

In [17]:
a[1,1] # accessing one specific element

4

In [20]:
a[0, :] # accessing first row

array([1, 2], dtype=int16)

In [21]:
a[: , 0] # Fetching first column

array([1, 3], dtype=int16)

In [26]:
a[: , 1] = (99, 99) # Updating a specific column
print(a)

[[ 1 99]
 [ 3 99]]


### Generating specific matrixes

In [31]:
np.ones((3, 3), dtype="int8") # creates arrays of 1s

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [32]:
np.zeros((3,3), dtype="int8") # creates arrays of 0s

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [34]:
np.full((2,2), 99) # creates arrays fileld with specific value

array([[99, 99],
       [99, 99]])

In [40]:
np.random.rand(2,2) # Generate random float values arrays

array([[0.04652306, 0.46851432],
       [0.081302  , 0.39715904]])

In [41]:
np.random.randint(7, size=(2,2)) # Generate random int values arrays 

array([[1, 6],
       [6, 2]])

In [43]:
np.identity(5) # Generate identity matrixes

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Transformations and Mathematical operations

In [45]:
a * 2

array([[2, 4],
       [6, 8]], dtype=int16)

In [46]:
a / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [47]:
a ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int16)

In [51]:
a + 5

array([[6, 7],
       [8, 9]], dtype=int16)

In [50]:
a.reshape((4)) # reshaping an array

array([1, 2, 3, 4], dtype=int16)

In [60]:
b = np.array([[1,2,3]])
np.repeat(b, 3, axis=0) # repeat the content of an specific array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [68]:
b = np.array([1,2,3])
c = np.array([4,5,6])
np.vstack([b,c])

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.hstack([b,c])

array([1, 2, 3, 4, 5, 6])