### Importing library and basic array

In [4]:
import numpy as np

a = np.array([[1,2],[3,4]], dtype="int16")
print(a)

[[1 2]
 [3 4]]


### Printing characteristcs of an Array

In [7]:
# number of dimentions
a.ndim

2

In [8]:
# shape of the array - this is a tuple with dimention's size
a.shape

(2, 2)

In [9]:
# basic data type
a.dtype

dtype('int8')

In [14]:
# number of elements in the array
a.size

4

In [13]:
# number of bytes used in the array
a.nbytes

8

In [16]:
# number of bytes of data type
a.itemsize

2

### Accessing and updating elements in array

In [17]:
# accessing one specific element
a[1,1]

4

In [20]:
# accessing first row
a[0, :]

array([1, 2], dtype=int16)

In [21]:
# Fetching first column
a[: , 0]

array([1, 3], dtype=int16)

In [26]:
# Updating a specific column
a[: , 1] = (99, 99)
print(a)

[[ 1 99]
 [ 3 99]]


### Generating specific matrixes

In [31]:
# creates arrays of 1s
np.ones((3, 3), dtype="int8")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [32]:
# creates arrays of 0s
np.zeros((3,3), dtype="int8")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [34]:
# creates arrays fileld with specific value
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [40]:
# Generate random float values arrays
np.random.rand(2,2)

array([[0.04652306, 0.46851432],
       [0.081302  , 0.39715904]])

In [41]:
# Generate random int values arrays 
np.random.randint(7, size=(2,2))

array([[1, 6],
       [6, 2]])

In [43]:
# Generate identity matrixes
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Transformations and Mathematical operations

In [45]:
a * 2

array([[2, 4],
       [6, 8]], dtype=int16)

In [46]:
a / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [47]:
a ** 2

array([[ 1,  4],
       [ 9, 16]], dtype=int16)

In [51]:
a + 5

array([[6, 7],
       [8, 9]], dtype=int16)

In [50]:
# reshaping an array
a.reshape((4))

array([1, 2, 3, 4], dtype=int16)

In [60]:
# repeat the content of an specific array
b = np.array([[1,2,3]])
np.repeat(b, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [68]:
b = np.array([1,2,3])
c = np.array([4,5,6])
np.vstack([b,c])

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.hstack([b,c])

array([1, 2, 3, 4, 5, 6])

### Statistics

In [9]:
# or a.max() - returns max value inside Array
np.max(a)

4

In [10]:
# or a.min() - returns min value inside Array
np.min(a)

1

In [17]:
# returns an array with max value of each internal Array
np.max(a, axis=1)

array([2, 4], dtype=int16)

In [21]:
# returns a summation of all elements in an array
np.sum(a)

10

In [27]:
# returns summation of rows
np.sum(a, axis=1)

array([3, 7])

In [31]:
# returns average
np.average(a)

2.5

### Linear Algebra

In [100]:
# Matrix multiplication
a = np.random.randint(7, size=(2,3))
b = np.random.randint(7, size=(3,2))
print(a)
print(b)
np.matmul(a,b)

[[6 2 0]
 [2 6 1]]
[[2 3]
 [4 6]
 [1 2]]


array([[20, 30],
       [29, 44]])

In [102]:
# Generating identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
# Determinant of a identity matrix is 1
c = np.identity(3)
np.linalg.det(c)

1.0

In [98]:
# inverted matrix (A * A**-1 == Determinant)
c = np.random.randint(7, size=(3,3))
print(c)
np.linalg.inv(c)

[[2 0 2]
 [2 3 3]
 [2 6 6]]


array([[ 0.        ,  1.        , -0.5       ],
       [-0.5       ,  0.66666667, -0.16666667],
       [ 0.5       , -1.        ,  0.5       ]])

### File IO - Reading and Writing

In [106]:
# Reading data from file
a = np.genfromtxt("data.txt", delimiter=",", dtype="int")
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [107]:
a[: , -1] = (99, 99)
a

array([[ 1,  2,  3,  4, 99],
       [ 6,  7,  8,  9, 99]])

In [108]:
# Writing array to file
np.savetxt("data_002.txt", a, fmt="%d", delimiter=",")

In [109]:
b = np.genfromtxt("data_002.txt", delimiter=",", dtype="int")
b

array([[ 1,  2,  3,  4, 99],
       [ 6,  7,  8,  9, 99]])

### Advanced Indexing

In [95]:
# Where in b is greater than 50
b > 50

array([[False, False, False, False,  True],
       [False, False, False, False,  True]])

In [79]:
# filter only values greater than 50
b[b > 50]

array([99, 99])

In [94]:
# multiple indexes at once
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,4,8]]

array([1, 5, 9])

In [91]:
# columns containing at least one value greater than 8
np.any(b > 8, axis=0)

array([False, False, False,  True,  True])

In [110]:
# columns containing all elements greater than 8
np.all(b > 8, axis=0)

array([False, False, False, False,  True])

In [111]:
# bolean logic and multiple conditions
((b > 3) & (b <8))

array([[False, False, False,  True, False],
       [ True,  True, False, False, False]])

In [118]:
example = np.arange(1,31).reshape(6,5)
example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [120]:
example[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [130]:
a = example[0:-2, 1:]
a[np.identity(4) == 1]

array([ 2,  8, 14, 20])

In [132]:
example[[0,1,2,3],[1,2,3,4]] 

array([ 2,  8, 14, 20])

In [145]:
example[[0, 4, 5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])